### PR TITLE
docs: fix typos

### PR DESCRIPTION
**Pull request by TehBrian**
re-pr of #331. for some reason the old pr wasn't updating - the branch didn't seem linked correctly.

### CODE REVIEW

**Comment by zml2008** [comment]
Looks ilke you're going to have to rebase this -- probably best to target 1.7.0-dev branch as well.

**Comment by broccolai** [comment]
Changing the version in the gradle.properties is not the correct way to update Gradle.
You can run `./gradlew wrapper --gradle-version=<version>`, the update the wrapper.

Also in the future, unless you have a reason for needing the update (like a new java version not working with our wrapper), don't worry about update the wrapper, core team will do it whenever we think it's necessary

**Comment by TehBrian** [comment]
I did run `./gradlew wrapper --gradle-version=7.4`

**Comment by jpenilla** [comment]
it's sometimes needed to run the task twice to ensure the wrapper jar is up to date - the jar doesn't always change with every gradle update - but I know it did with 7.4 and this pr doesn't touch the wrapper jar.

for the reason broccolai mentioned though the gradle update should be dropped from this pr.

on a related note we prefer if prs are kept to address a single thing rather than grouping two unrelated sets of changes

**Comment by TehBrian** [comment]
odd, I just ran both `./gradlew wrapper --gradle-version=7.4` and `./gradlew wrapper` several times and there's no difference. anyway, I'll drop the wrapper commit.

**Review by Citymonstret — APPROVED** [review]

**Pull request merged**
