### PR TITLE
JDA Slash commands platform implementation

### PR DESCRIPTION
**Pull request by solonovamax**
Create new JDA Slash commands platform implementation.

Creating this PR, but marking it as draft, so that I can receive feedback on it as I progress.

### CODE REVIEW

**Comment by solonovamax** [comment]
pain.
image

**Comment by PierreSchwang** [comment]
I guess this is kind of dead? :/

**Comment by solonovamax** [comment]
@PierreSchwang a little. I am considering starting up on it again, though.

**Comment by PierreSchwang** [comment]
@solonovamax nice to hear that, i started on a basic implementation which does work indeed, but subcommands and subcommand groups are still pain

**Comment by solonovamax** [comment]
@PierreSchwang can you link me your repo? I might look at the changes and try to incorporate it in this

**Comment by darbyjack** [comment]
As of yesterday, the final version of 4.x was released, and therefore marked as the LTS version. If you just upgraded to that, would that allow you to not have to maintain 2 separate versions in the Versions file for JDA?

**Comment by solonovamax** [comment]
Branch has been rebased on top of 1.8.0-dev, btw

So, all the other commits that used to be showing that weren't part of this branch now no longer show

**Comment by jpenilla** [comment]
There is a JDA5 impl with slash command support for v2 in https://github.com/Incendo/cloud-discord

**Pull request closed without merging**
