### PR TITLE
chore: `List<Suggestion>` -> `Iterable<Suggestion>`

### PR DESCRIPTION
**Pull request by Citymonstret**

### CODE REVIEW

**Comment by solonovamax** [comment]
why `Iterable` and not `Collection`?

that seems more appropriate to me

**Comment by jpenilla** [comment]
Might as well change BlockingSuggestionProvider.Strings as well

**Comment by jpenilla** [comment]
Being able to return an iterable is more flexible than a collection, but it's also a little more annoying to deal with on the consumer side...

**Comment by broccolai** [comment]
Would prefer Iterable

**Pull request merged**
